name: Download PDF

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download PDF
        run: |
          curl -L -o "FEC_Survey.pdf" "https://www.academia.edu/89482758/A_Survey_on_FEC_Codes_for_100_G_and_Beyond_Optical_Networks"

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add FEC_Survey.pdf
          git commit -m "Add FEC Survey PDF"
          git push
